Loaded module: python3/3.6.2
Loaded dependency [numpy/1.13.1-python-3.6.2-openblas-0.2.20]: openblas/0.2.20
Loaded module: numpy/1.13.1-python-3.6.2-openblas-0.2.20

Loading numpy/1.13.1-python-3.6.2-openblas-0.2.20
  Loading requirement: openblas/0.2.20
Loaded module: scipy/0.19.1-python-3.6.2
Loaded module: matplotlib/2.0.2-python-3.6.2
Loaded module: cuda/11.6
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Error executing job with overrides: []
Traceback (most recent call last):
  File "/zhome/8d/a/147395/masterproject/masterproject/src/train_model.py", line 54, in train
    model.train("traindata.csv", args=args)
  File "/zhome/8d/a/147395/miniconda3/envs/src/lib/python3.11/site-packages/happytransformer/happy_text_classification.py", line 51, in train
    super(HappyTextClassification, self).train(input_filepath, args, eval_filepath)
  File "/zhome/8d/a/147395/miniconda3/envs/src/lib/python3.11/site-packages/happytransformer/happy_transformer.py", line 106, in train
    train_tok_data, eval_tok_data = self._preprocess_data_train(input_filepath=input_filepath,
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/8d/a/147395/miniconda3/envs/src/lib/python3.11/site-packages/happytransformer/happy_transformer.py", line 142, in _preprocess_data_train
    all_raw_data = load_dataset(file_type, data_files={"train": input_filepath}, split="train")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/8d/a/147395/miniconda3/envs/src/lib/python3.11/site-packages/datasets/load.py", line 2523, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/8d/a/147395/miniconda3/envs/src/lib/python3.11/site-packages/datasets/load.py", line 2195, in load_dataset_builder
    dataset_module = dataset_module_factory(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/8d/a/147395/miniconda3/envs/src/lib/python3.11/site-packages/datasets/load.py", line 1736, in dataset_module_factory
    ).get_module()
      ^^^^^^^^^^^^
  File "/zhome/8d/a/147395/miniconda3/envs/src/lib/python3.11/site-packages/datasets/load.py", line 1120, in get_module
    data_files = DataFilesDict.from_patterns(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/8d/a/147395/miniconda3/envs/src/lib/python3.11/site-packages/datasets/data_files.py", line 689, in from_patterns
    DataFilesList.from_patterns(
  File "/zhome/8d/a/147395/miniconda3/envs/src/lib/python3.11/site-packages/datasets/data_files.py", line 594, in from_patterns
    resolve_pattern(
  File "/zhome/8d/a/147395/miniconda3/envs/src/lib/python3.11/site-packages/datasets/data_files.py", line 383, in resolve_pattern
    raise FileNotFoundError(error_msg)
FileNotFoundError: Unable to find '/zhome/8d/a/147395/masterproject/masterproject/traindata.csv'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
make: *** [train] Error 1
